### ISSUE TITLE
Install from clean causes rifraf error

### ISSUE THREAD

**Issue by coderberry** [toranb/ember-cli-store-example#1]
```
$ npm install
...
$ bower install
...
$ ember server
version: 0.1.5
Looks like you have a different program called watchman, falling back to NodeWatcher
Livereload server on port 35729
Serving on http://0.0.0.0:4200/
undefined is not a function
TypeError: undefined is not a function
    at rimraf (/Users/eberry/tmp/ember-cli-store-example/node_modules/ember-cli/node_modules/broccoli-caching-writer/node_modules/rimraf/rimraf.js:57:13)
    at lib$rsvp$node$$tryApply (/Users/eberry/tmp/ember-cli-store-example/node_modules/ember-cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:1467:11)
    at lib$rsvp$node$$handleValueInput (/Users/eberry/tmp/ember-cli-store-example/node_modules/ember-cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:1567:20)
    at fn (/Users/eberry/tmp/ember-cli-store-example/node_modules/ember-cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:1555:18)
    at /Users/eberry/tmp/ember-cli-store-example/node_modules/ember-cli/node_modules/broccoli-caching-writer/index.js:100:14
    at lib$rsvp$$internal$$tryCatch (/Users/eberry/tmp/ember-cli-store-example/node_modules/ember-cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/eberry/tmp/ember-cli-store-example/node_modules/ember-cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:501:17)
    at lib$rsvp$$internal$$publish (/Users/eberry/tmp/ember-cli-store-example/node_modules/ember-cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:472:11)
    at lib$rsvp$asap$$flush (/Users/eberry/tmp/ember-cli-store-example/node_modules/ember-cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:1290:9)
    at process._tickCallback (node.js:349:13)
```

**Comment by toranb** [comment]
I just updated to ember-cli 0.2.0 and ember 1.11 beta 5 - all is good now :)
